name: Jason L. Jordan
favicon: null
layout_spectrum: 0.5041
typography_spectrum: 0.74919
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
