name: Jason L. Jordan
favicon: null
layout_spectrum: 0.9907580309081823
typography_spectrum: 0.5478531992994249
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5
  lightness: 0.5511598016601056
  saturation: 0.19869337161071599
  rhythmicContrast: 0.4366377703845501
purpose: []
